language: php
sudo: false
php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install: sh travis.sh
script: cd _test && ./phpunit.phar --stderr --group plugin_include
